title: 'creativeslant.com | zachary jean paradis'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 0.2608626056462526
  rhythmicContrast: 0.5
  brandColors:
    - '#3b5375'
    - '#da5431'
    - '#e0e6dc'
    - '#120403'
    - '#96a4b7'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: creativeslant
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4121864
layout_spectrum: 0.9569892
